import { Image } from "react-grid-gallery";

export interface CustomImage extends Image {
  original: string;
}

export const images: CustomImage[] = [
  {
    src: "/images/gallery/pack1/61 Antes_25_11zon.webp",
    original: "/images/gallery/pack1/61 Antes_25_11zon.webp",
    width: 1536,
    height: 2048,
    alt: "61 After",
    tags: [{ value: "After", title: "After" }],
  },
  {
    src: "/images/gallery/pack1/62 Despues_26_11zon.webp",
    original: "/images/gallery/pack1/62 Despues_26_11zon.webp",
    width: 1536,
    height: 2048,
    alt: "62 Before",
    tags: [{ value: "Before", title: "Before" }],
  },
  {
    src: "/images/gallery/pack1/57 Antes_21_11zon.webp",
    original: "/images/gallery/pack1/57 Antes_21_11zon.webp",
    width: 1536,
    height: 2048,
    alt: "57 After",
    tags: [{ value: "After", title: "After" }],
  },
  {
    src: "/images/gallery/pack1/58 Despues_22_11zon.webp",
    original: "/images/gallery/pack1/58 Despues_22_11zon.webp",
    width: 1536,
    height: 2048,
    alt: "58 Before",
    tags: [{ value: "Before", title: "Before" }],
  },

  {
    src: "/images/gallery/pack1/46 Antes_10_11zon.webp",
    original: "/images/gallery/pack1/46 Antes_10_11zon.webp",
    width: 1536,
    height: 2048,
    alt: "46 Before",
    tags: [{ value: "Before", title: "Before" }],
  },
  {
    src: "/images/gallery/pack1/47 Despues_11_11zon.webp",
    original: "/images/gallery/pack1/47 Despues_11_11zon.webp",
    width: 1536,
    height: 2048,
    alt: "47 After",
    tags: [{ value: "After", title: "After" }],
  },
  {
    src: "/images/gallery/pack1/42 Antes_6_11zon.webp",
    original: "/images/gallery/pack1/42 Antes_6_11zon.webp",
    width: 1536,
    height: 2048,
    alt: "42 Before",
    tags: [{ value: "Before", title: "Before" }],
  },
  {
    src: "/images/gallery/pack1/40 Antes_4_11zon.webp",
    original: "/images/gallery/pack1/40 Antes_4_11zon.webp",
    width: 1536,
    height: 2048,
    alt: "40 Before",
    tags: [{ value: "Before", title: "Before" }],
  },
  {
    src: "/images/gallery/pack1/41 Despues_5_11zon.webp",
    original: "/images/gallery/pack1/41 Despues_5_11zon.webp",
    width: 1536,
    height: 2048,
    alt: "41 After",
    tags: [{ value: "After", title: "After" }],
  },
  {
    src: "/images/gallery/pack1/38 Antes_2_11zon.webp",
    original: "/images/gallery/pack1/38 Antes_2_11zon.webp",
    width: 1536,
    height: 2048,
    alt: "38 After",
    tags: [{ value: "After", title: "After" }],
  },
  {
    src: "/images/gallery/35 ANTES.webp",
    original: "/images/gallery/35 ANTES.webp",
    width: 1536,
    height: 2048,
    alt: "35 Before",
    tags: [{ value: "Before", title: "Before" }],
  },
  {
    src: "/images/gallery/36 DESPUES.webp",
    original: "/images/gallery/36 DESPUES.webp",
    width: 1536,
    height: 2048,
    alt: "36 After",
    tags: [{ value: "After", title: "After" }],
  },
  {
    src: "/images/gallery/30 ANTES.webp",
    original: "/images/gallery/30 ANTES.webp",
    width: 1536,
    height: 2048,
    alt: "30 Before",
    tags: [{ value: "Before", title: "Before" }],
  },
  {
    src: "/images/gallery/31 DESPUES.webp",
    original: "/images/gallery/31 DESPUES.webp",
    width: 1536,
    height: 2048,
    alt: "31 After",
    tags: [{ value: "After", title: "After" }],
  },
  {
    src: "/images/gallery/29 ANTES.webp",
    original: "/images/gallery/29 ANTES.webp",
    width: 1536,
    height: 2048,
    alt: "29 Before",
    tags: [{ value: "Before", title: "Before" }],
  },
  {
    src: "/images/gallery/29 DESPUES.webp",
    original: "/images/gallery/29 DESPUES.webp",
    width: 1536,
    height: 2048,
    alt: "29 After",
    tags: [{ value: "After", title: "After" }],
  },
  {
    src: "/images/gallery/28 ANTES.webp",
    original: "/images/gallery/28 ANTES.webp",
    width: 1536,
    height: 2048,
    alt: "28 Before",
    tags: [{ value: "Before", title: "Before" }],
  },
  {
    src: "/images/gallery/28 DESPUES.webp",
    original: "/images/gallery/28 DESPUES.webp",
    width: 1536,
    height: 2048,
    alt: "28 Before",
    tags: [{ value: "After", title: "After" }],
  },
  {
    src: "/images/gallery/26B.webp",
    original: "/images/gallery/26B.webp",
    width: 1536,
    height: 2048,
    alt: "26B",
    tags: [{ value: "Before", title: "Before" }],
  },
  {
    src: "/images/gallery/26A.webp",
    original: "/images/gallery/26A.webp",
    width: 1536,
    height: 2048,
    alt: "26A",
    tags: [{ value: "After", title: "After" }],
  },
  {
    src: "/images/gallery/door-before.webp",
    original: "/images/gallery/door-before.webp",
    width: 720,
    height: 960,
    alt: "door-before",
    tags: [{ value: "Before", title: "Before" }],
    caption: "Before",
  },
  {
    src: "/images/gallery/door-after.webp",
    original: "/images/gallery/door-after.webp",
    width: 720,
    height: 960,
    alt: "door-after",
    tags: [{ value: "After", title: "After" }],
    caption: "After",
  },
  {
    src: "/images/gallery/fence_before.webp",
    original: "/images/gallery/fence_before.webp",
    width: 720,
    height: 960,
    alt: "fence-before",
    tags: [{ value: "Before", title: "Before" }],
    caption: "Before",
  },
  {
    src: "/images/gallery/fence_after.webp",
    original: "/images/gallery/fence_after.webp",
    width: 720,
    height: 960,
    alt: "fence-after",
    tags: [{ value: "After", title: "After" }],
    caption: "After",
  },
  {
    src: "/images/gallery/pink_house_before.webp",
    original: "/images/gallery/pink_house_before.webp",
    width: 1536,
    height: 2048,
    alt: "pink-house-before",
    tags: [{ value: "Before", title: "Before" }],
    caption: "Before",
  },
  {
    src: "/images/gallery/pink_house_after.webp",
    original: "/images/gallery/pink_house_after.webp",
    width: 1536,
    height: 2048,
    alt: "pink-house-after",
    tags: [{ value: "After", title: "After" }],
    caption: "After",
  },
  {
    src: "/images/gallery/5L.webp",
    original: "/images/gallery/5L.webp",
    tags: [{ value: "After", title: "After" }],
    alt: "5L",
    width: 1536,
    height: 2048,
  },
  {
    src: "/images/gallery/6L.webp",
    original: "/images/gallery/6L.webp",
    tags: [{ value: "After", title: "After" }],
    alt: "6L",
    width: 1536,
    height: 1290,
  },
  {
    src: "/images/gallery/7L.webp",
    original: "/images/gallery/7L.webp",
    tags: [{ value: "Before", title: "Before" }],
    alt: "7L",
    width: 1536,
    height: 2048,
  },
  {
    src: "/images/gallery/13L.webp",
    original: "/images/gallery/13L.webp",
    tags: [{ value: "After", title: "After" }],
    alt: "13L",
    width: 1536,
    height: 2048
  },
  {
    src: "/images/gallery/14L.webp",
    original: "/images/gallery/14L.webp",
    tags: [{ value: "Before", title: "Before" }],
    alt: "14L",
    width: 1536,
    height: 2048
  },
  {
    src: "/images/gallery/15L.webp",
    original: "/images/gallery/15L.webp",
    tags: [{ value: "After", title: "After" }],
    alt: "15L",
    width: 1536,
    height: 2048
  },
  {
    src: "/images/gallery/19.webp",
    original: "/images/gallery/19.webp",
    tags: [{ value: "Before", title: "Before" }],
    alt: "19L",
    width: 1536,
    height: 2048
  },
  {
    src: "/images/gallery/20.webp",
    original: "/images/gallery/20.webp",
    tags: [{ value: "After", title: "After" }],
    alt: "20L",
    width: 1536,
    height: 2048
  },
  {
    src: "/images/gallery/21.webp",
    original: "/images/gallery/21.webp",
    tags: [{ value: "Before", title: "Before" }],
    alt: "21L",
    width: 1536,
    height: 2048
  },
  {
    src: "/images/gallery/22.webp",
    original: "/images/gallery/22.webp",
    tags: [{ value: "After", title: "After" }],
    alt: "22L",
    width: 1536,
    height: 2048
  },
  {
    src: "/images/gallery/23.webp",
    original: "/images/gallery/23.webp",
    tags: [{ value: "Before", title: "Before" }],
    alt: "23L",
    width: 1536,
    height: 2048
  },
  {
    src: "/images/gallery/24.webp",
    original: "/images/gallery/24.webp",
    tags: [{ value: "After", title: "After" }],
    alt: "24L",
    width: 1536,
    height: 2048,
  },
];
